### PR TITLE
LittleFS for nand flash

### PR DESCRIPTION
**Pull request by fpoussin**
Since bad blocks can happen with NAND flash, we need a reliable filesystem that can handle those.
I've also added all the required tools with it and cleanup the Makefiles.

This is a work in progress, I'll be doing more testing.

### CODE REVIEW

**Comment by szemzoa** [comment]
Please give me a few days to test it. Regarding the sunxi_spi: set clock to 96MHz, I think it's not right.
The formula is (User manual page 121):  SCLK = Clock Source/M/N.
I reworked the spi clock setup, but had not time to test it properly, can you look at it?




diff -urN awboot.git/.build_revision awboot.git-spi-clk-rework/.build_revision
--- awboot.git/.build_revision	2022-11-04 12:10:32.000000000 +0100
+++ awboot.git-spi-clk-rework/.build_revision	2022-11-11 08:01:47.000000000 +0100
@@ -1 +1 @@
-6090
+6091
diff -urN awboot.git/Makefile awboot.git-spi-clk-rework/Makefile
--- awboot.git/Makefile	2022-11-07 08:15:58.000000000 +0100
+++ awboot.git-spi-clk-rework/Makefile	2022-11-11 08:03:06.000000000 +0100
@@ -101,9 +101,11 @@
 	rm -f *.o
 	echo "  CC    $<"
 	rm -f $(TARGET)
-	rm -f $(TARGET).bin
 	rm -f $(TARGET).map
-	rm -f $(TARGET).elf
+	rm -f $(TARGET)-boot.bin
+	rm -f $(TARGET)-boot.elf
+	rm -f $(TARGET)-fel.bin
+	rm -f $(TARGET)-fel.elf
 	rm -f .deps
 	rm -f .dep/*.d
 	rm -f $(MKSUNXI)
diff -urN awboot.git/arch/arm32/mach-t113s3/sunxi_spi.c awboot.git-spi-clk-rework/arch/arm32/mach-t113s3/sunxi_spi.c
--- awboot.git/arch/arm32/mach-t113s3/sunxi_spi.c	2022-11-07 11:55:32.000000000 +0100
+++ awboot.git-spi-clk-rework/arch/arm32/mach-t113s3/sunxi_spi.c	2022-11-11 07:59:38.000000000 +0100
@@ -28,6 +28,7 @@
 #include "div.h"
 #include "reg-ccu.h"
 #include "sunxi_spi.h"
+#include "sunxi_clk.h"
 #include "debug.h"
 
 enum {
@@ -46,10 +47,6 @@
 	SPI_RXD	= 0x300,
 };
 
-#define SPI0_CLK_DIV_NONE	0x0000
-#define SPI0_CLK_DIV_BY_2       0x1000
-#define SPI0_CLK_DIV_BY_4       0x1001
-
 enum {
 	OPCODE_RDID			= 0x9f,
 	OPCODE_GET_FEATURE		= 0x0f,
@@ -66,12 +63,6 @@
 	OPCODE_RESET			= 0xff,
 };
 
-/*
-#define SPINAND_PAGE_BITS	(11)
-#define SPINAND_PAGE_MASK	((1 << SPINAND_PAGE_BITS) - 1)
-#define SPINAND_PAGE_SIZE	(1 << SPINAND_PAGE_BITS)
-*/
-
 #define SPINAND_ID(...)			{ .val = { __VA_ARGS__ }, .len = sizeof((uint8_t[]){ __VA_ARGS__ }) }
 
 static const struct spinand_info_t spinand_infos[] = {
@@ -118,9 +109,116 @@
 	{ "MT29F8G01ADAFD",  SPINAND_ID(0x2c, 0x46),       4096, 256,  64, 2048, 1, 2 },
 };
 
-void sunxi_spi_init(struct sunxi_spi_t *spi)
+/* SPI Clock Control Register Bit Fields & Masks,default:0x0000_0002 */
+#define SPI_CLK_CTL_CDR2        (0xFF <<  0) /* Clock Divide Rate 2,master mode only : SPI_CLK = AHB_CLK/(2*(n+1)) */
+#define SPI_CLK_CTL_CDR1        (0xF  <<  8) /* Clock Divide Rate 1,master mode only : SPI_CLK = AHB_CLK/2^n */
+#define SPI_CLK_CTL_DRS         (0x1  << 12) /* Divide rate select,default,0:rate 1;1:rate 2 */
+
+#define SPI_MOD_CLK		200000000
+
+static void spi_set_clk(struct sunxi_spi_t *spi, u32 spi_clk, u32 ahb_clk, u32 cdr)
+{
+    uint32_t reg_val = 0;
+    uint32_t div_clk = 0;
+
+        debug("spi-nand: set spi clock=%dMHz, mclk=%dMHz\r\n", spi_clk / 1000 / 1000, ahb_clk / 1000 / 1000);
+        reg_val = read32(spi->base + SPI_CCR);
+
+        /* CDR2 */
+        if (cdr) {
+                div_clk = ahb_clk / (spi_clk * 2) - 1;
+                reg_val &= ~SPI_CLK_CTL_CDR2;
+                reg_val |= (div_clk | SPI_CLK_CTL_DRS);
+                debug("CDR2 - n = %d\r\n", div_clk);
+        } else { /* CDR1 */
+                while (ahb_clk > spi_clk) {
+                        div_clk++;
+                        ahb_clk >>= 1;
+                }
+                reg_val &= ~(SPI_CLK_CTL_CDR1 | SPI_CLK_CTL_DRS);
+                reg_val |= (div_clk << 8);
+                debug("CDR1 - n = %d\r\n", div_clk);
+        }
+
+        write32(spi->base + SPI_CCR, reg_val);
+}
+
+
+static int spi_clk_init(uint32_t mod_clk)
+{
+    uint32_t rval;
+    uint32_t source_clk = 0;
+    uint32_t m, n, divi, factor_m;
+
+        /* SCLK = src/M/N */
+        /* N: 00:1 01:2 10:4 11:8 */
+        /* M: factor_m + 1 */
+        source_clk = sunxi_clk_get_peri1x_rate();
+
+        divi = div((source_clk + mod_clk - 1) , mod_clk);
+        divi = divi == 0 ? 1 : divi;
+        if (divi > 128) {
+                m = 1;
+                n = 0;
+                return -1;
+        } else if (divi > 64) {
+                n = 3;
+                m = divi >> 3;
+        } else if (divi > 32) {
+                n = 2;
+                m = divi >> 2;
+        } else if (divi > 16) {
+                n = 1;
+                m = divi >> 1;
+        } else {
+                n = 0;
+                m = divi;
+        }
+
+        factor_m = m - 1;
+        rval = (1U << 31) | (0x1 << 24) | (n << 8) | factor_m;
+
+        /**sclk_freq = source_clk / (1 << n) / m; */
+//        debug("spi-nand: parent_clk=%dMHz, div=%d, n=%d, m=%d\r\n", source_clk / 1000 / 1000, divi, n, m);
+	write32(T113_CCU_BASE + CCU_SPI0_CLK_REG, rval);
+
+        return 0;
+}
+
+#if 0
+int sunxi_get_spi_clk()
+{
+    u32 reg_val = 0;
+    u32 src = 0, clk = 0, sclk_freq = 0;
+    u32 n, m;
+
+        reg_val = read32(T113_CCU_BASE + CCU_SPI0_CLK_REG);
+        src = (reg_val >> 24) & 0x7;
+        n = (reg_val >> 8) & 0x3;
+        m = ((reg_val >> 0) & 0xf) + 1;
+
+        switch(src) {
+                case 0:
+                        clk = 24000000;
+                        break;
+                case 1:
+                        clk = sunxi_clk_get_peri1x_rate();
+                        break;
+                default:
+                        clk = 0;
+                        break;
+        }
+
+        sclk_freq = div(div(clk, (1 << n)), m);
+	debug("sclk_freq=%dMHz, reg_val: %x, n=%d, m=%d\r\n", sclk_freq / 1000 / 1000, reg_val, n, m);
+
+        return sclk_freq;
+}
+#endif
+
+int sunxi_spi_init(struct sunxi_spi_t *spi)
 {
-    uint32_t addr, val;
+    uint32_t val;
 
         /* Config SPI pins */
         sunxi_gpio_init(spi->gpio_cs.pin, spi->gpio_cs.mux);
@@ -129,31 +227,22 @@
         sunxi_gpio_init(spi->gpio_miso.pin, spi->gpio_miso.mux);
 
 	/* Deassert spi0 reset */
-	addr = T113_CCU_BASE + CCU_SPI_BGR_REG;
-	val = read32(addr);
+	val = read32(T113_CCU_BASE + CCU_SPI_BGR_REG);
 	val |= (1 << 16);
-	write32(addr, val);
+	write32(T113_CCU_BASE + CCU_SPI_BGR_REG, val);
 
 	/* Open the spi0 gate */
-	addr = T113_CCU_BASE + CCU_SPI0_CLK_REG;
-	val = read32(addr);
+	val = read32(T113_CCU_BASE + CCU_SPI_BGR_REG);
 	val |= (1 << 31);
-	write32(addr, val);
+	write32(T113_CCU_BASE + CCU_SPI_BGR_REG, val);
 
 	/* Open the spi0 bus gate */
-	addr = T113_CCU_BASE + CCU_SPI_BGR_REG;
-	val = read32(addr);
+	val = read32(T113_CCU_BASE + CCU_SPI_BGR_REG);
 	val |= (1 << 0);
-	write32(addr, val);
-
-	/* Select 24MHz for spi0 clk */
-	addr = T113_CCU_BASE + CCU_SPI0_CLK_REG;
-	val = read32(addr);
-	val &= ~(0x3 << 24);
-	write32(addr, val);
+	write32(T113_CCU_BASE + CCU_SPI_BGR_REG, val);
 
-	/* Set spi clock rate control register */
-	write32(spi->base + SPI_CCR, SPI0_CLK_DIV_NONE);
+	spi_clk_init(SPI_MOD_CLK);
+	spi_set_clk(spi, spi->clk_rate, SPI_MOD_CLK, 0);
 
 	/* Enable spi0 and do a soft reset */
 	val = read32(spi->base + SPI_GCR);
@@ -171,6 +260,8 @@
 	val = read32(spi->base + SPI_FCR);
 	val |= (1 << 31) | (1 << 15);
 	write32(spi->base + SPI_FCR, val);
+
+	return 0;
 }
 
 void sunxi_spi_exit(struct sunxi_spi_t *spi)
@@ -383,10 +474,9 @@
     uint8_t val;
 
 	spinand_reset(spi);
+	spinand_wait_for_busy(spi);
 
 	if (spinand_info(spi) == 0) {
-//	    spinand_reset(spi);
-	    spinand_wait_for_busy(spi);
 
 	    if ((spinand_get_feature(spi, OPCODE_FEATURE_PROTECT, &val) == 0) && (val != 0x0)) {
 	    	spinand_set_feature(spi, OPCODE_FEATURE_PROTECT, 0x0);
diff -urN awboot.git/arch/arm32/mach-t113s3/sunxi_spi.h awboot.git-spi-clk-rework/arch/arm32/mach-t113s3/sunxi_spi.h
--- awboot.git/arch/arm32/mach-t113s3/sunxi_spi.h	2022-10-28 14:12:53.000000000 +0200
+++ awboot.git-spi-clk-rework/arch/arm32/mach-t113s3/sunxi_spi.h	2022-11-07 13:56:20.000000000 +0100
@@ -21,6 +21,7 @@
 struct sunxi_spi_t {
 	uint32_t    base;
 	uint8_t     id;
+	uint32_t    clk_rate;
 	gpio_mux_t  gpio_cs;
 	gpio_mux_t  gpio_sck;
 	gpio_mux_t  gpio_miso;
@@ -29,7 +30,7 @@
 	struct spinand_info_t info;
 };
 
-extern void sunxi_spi_init(struct sunxi_spi_t *spi);
+extern int sunxi_spi_init(struct sunxi_spi_t *spi);
 extern int spinand_detect(struct sunxi_spi_t *spi);
 extern uint64_t spinand_read(struct sunxi_spi_t *spi, uint8_t *buf, uint64_t offset, uint64_t count);
 
diff -urN awboot.git/board.c awboot.git-spi-clk-rework/board.c
--- awboot.git/board.c	2022-11-04 12:00:04.000000000 +0100
+++ awboot.git-spi-clk-rework/board.c	2022-11-07 13:59:40.000000000 +0100
@@ -43,6 +43,7 @@
 struct sunxi_spi_t sunxi_spi0 = {
 	.base 	= 0x04025000,
 	.id 	= 0,
+	.clk_rate = 50000000,
 	.gpio_cs = { GPIO_PIN(PORTC, 3), GPIO_PERIPH_MUX2 },
 	.gpio_sck = { GPIO_PIN(PORTC, 2), GPIO_PERIPH_MUX2 },
 	.gpio_mosi = { GPIO_PIN(PORTC, 4), GPIO_PERIPH_MUX2 },
diff -urN awboot.git/build_revision.h awboot.git-spi-clk-rework/build_revision.h
--- awboot.git/build_revision.h	2022-11-04 12:10:32.000000000 +0100
+++ awboot.git-spi-clk-rework/build_revision.h	2022-11-11 08:01:47.000000000 +0100
@@ -1,4 +1,4 @@
 // Generated by make, DO NOT EDIT
 #ifndef __BUILD_REVISION_H__
-#define BUILD_REVISION 6090
+#define BUILD_REVISION 6091
 #endif

**Comment by szemzoa** [comment]
Please give me a few days to test it. Regarding the sunxi_spi: set clock to 96MHz, I think it's not right.
The formula is (User manual page 121): SCLK = Clock Source/M/N.
I reworked the spi clock setup, but had not time to test it properly, can you look at it?

[spi_clk_rework.txt](https://github.com/szemzoa/awboot/files/9987573/spi_clk_rework.txt)

**Comment by fpoussin** [comment]
No worries, I'll still need some time for testing as well. 
As for SPI, I assumed `(SCLK/M)*N` as it's the usual way PLL works but you are right, so I've dropped that commit.
I'll give your code a try.
Thanks

**Comment by fpoussin** [comment]
Well, it loads. Now I can have a look at the LFS code.
```
Allwinner T113-loader
DRAM SIZE = 128M
DRAM simple test OK.
CPU freq=1200 MHz
spi-nand: set spi clock=50MHz, mclk=200MHz
CDR1 - n = 2
spi-nand: W25N01GV detected
oops, something went wrong..
```

**Comment by fpoussin** [comment]
I've opened another PR with all the changes without LFS as it's taking me more time to test than expected. This will be easier to review and merge.

**Comment by fpoussin** [comment]
Closing, I'll make a new one later on.

**Pull request closed without merging**
